version: "3.7"

services:
  db:
    image: postgres:11
    network_mode: bridge
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: ${DB_PORT}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432
  api:
    restart: always
    build:
      context: .
      target: production
    volumes:
      - .:/usr/src/app:delegated
      - /usr/src/app/dist
      - /usr/src/app/node_modules
    ports:
      - ${VIRTUAL_PORT}
    command: "node dist/main"
    env_file: ./.env
    network_mode: bridge
    tty: true
    links:
      - "db"
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
    logging:
      options:
        max-size: "10m"
        max-file: "3"


